### signUp
@url_dev = http://localhost:3052/v1/api

POST {{url_dev}}/shop/signupjlk
Content-Type: application/json

{
  "name": "tan",
  "email": "tanvo9930@gmail.com",
  "password": "pass"
}

### check api key before signUp
POST {{url_dev}}/shop/signup
x-api-key: 123
Content-Type: application/json

{
  "name": "tan",
  "email": "tanvo9936@gmail.com",
  "password": "pass"
}
